name: Build Only (Root)

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3

        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
          gradle-home-cache-cleanup: true

      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
